### ISSUE TITLE
Python 3 causes errors, would be useful info in readme

### ISSUE THREAD

**Issue by ryliejamesthomas** [bdoms/tumblr_backup#19]
Not sure how big a deal this is when people can always run it with an older version, but I think it's worth mentioning in the readme that this requires Python 2.

Thanks for the nice script!, saved me a lot of hassle <3

**Comment by bdoms** [comment]
The script is now compatible with Python 3 as of https://github.com/bdoms/tumblr_backup/commit/743f247780d3760ea00b6bef092ad5dafe515445

It was mostly just print statements and imports, though there were a few cases where encoding and byte strings had to be special cased.
